- src/index.ts
- tests/index.spec.ts
> :bug: extend DefineStoreOptionsBase

- .eslintignore
- examples/nuxt/.gitignore
- examples/nuxt/.npmrc
- examples/nuxt/app.vue
- examples/nuxt/nuxt.config.ts
- examples/nuxt/package.json
- examples/nuxt/plugins/persistedstate.ts
- examples/nuxt/stores/user.ts
- examples/nuxt/tsconfig.json
- examples/vue/.gitignore
- examples/vue/.npmrc
- examples/vue/index.html
- examples/vue/package.json
- examples/vue/src/App.vue
- examples/vue/src/env.d.ts
- examples/vue/src/main.ts
- examples/vue/src/stores/user.ts
- examples/vue/tsconfig.json
- examples/vue/vite.config.ts
> add example projects

- README.md
> :memo: add install command

- README.md
This PR fixes a bunch of issues in the readme.
I don't think these changes need an issue.
> 📜 Improve Readme

- src/pick.ts
This PR improves `src/pick.ts`'s typings.
I don't think this needs an issue
> 🏷️ Improve Pick Typings

- README.md
- src/index.ts
- tests/index.spec.ts
> :sparkles: add factory function

- src/index.ts
- src/normalize.ts
add normalizeOptions，Easy to expand options later
> chore: add normalizeOptions

- src/plugin.ts
> :bug: fix nuxt cookie encoding

- src/plugin.ts
- src/types.ts
> :sparkles: add cookieOptions

- src/core/plugin.ts
Subscribe to mutations in detached mode
closes #101
> :bug: subscribe to mutations in detached mode

- README.md
> Fixed Minor Typo

- docs/frameworks/nuxt-3.md
Add documentation regarding nuxt plugin order.
#124
> :memo: add nuxt plugin order docs

- docs/guide/advanced.md
> 📄 fix inaccurate link positioning

- packages/plugin/src/plugin.ts
> :adhesive_bandage: map store methods before rehydration

- docs/guide/advanced.md
- packages/plugin/src/plugin.ts
- packages/plugin/src/types.ts
- packages/plugin/tests/plugin.spec.ts
> :sparkles: auto mode

- docs/zh/guide/advanced.md
- docs/zh/guide/index.md
Synchronize the Chinese translation with the English version.
> 📝 sync with English version

- docs/zh/guide/index.md
change 'persistent' to 'persist'
change the attrubute name from 'persistent' to 'presist', maybe this is the old attr or a missspelling.
N/A
N/A
> attr name fix

- docs/guide/advanced.md
> :pencil2: fix typo

- packages/nuxt/package.json
> feat: upgrade to @pinia/nuxt@0.5.x

- CONTRIBUTING.md
see https://github.com/egoist/tsup/issues/1134
> docs(contributing): update tsup link

- README.md
- docs/guide/index.md
- docs/zh/guide/index.md
- packages/plugin/README.md
fix wrong pnpm add package command in document.
None
https://pnpm.io/cli/add
> :memo: fix wrong pnpm command in doc

- README.md
> chore: update Nuxt links in README.md

- package.json
Add `iife` (`umd/global`) build.
#348
> build: export iife build

- docs/zh/guide/config.md
Fix this afterHydrate description issue
> docs: fix the afterHydrate describe
